name: Build Android
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Поднимаем версию до 20, чтобы метод .toReversed() работал

      - name: Fix package.json for Build
        run: |
          sed -i '/@workspace\/api-client-react/d' package.json
          sed -i 's/"catalog:"/"*"/g' package.json
          sed -i 's/catalog:/*/g' package.json
          sed -i 's/,,/,/g' package.json
          sed -i 's/, \}/ \}/g' package.json

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Build Project
        run: npx expo export
