name: Build Android
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Fix package.json & app.json
        run: |
          sed -i '/@workspace\/api-client-react/d' package.json
          sed -i 's/"catalog:"/"*"/g' package.json
          sed -i 's/catalog:/*/g' package.json
          if ! grep -q "package" app.json; then
            sed -i '/"android": {/a \      "package": "com.russumaxim.ghostmessenger",' app.json
          fi

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Build Android APK
        env:
          NODE_ENV: production
        run: |
          npx expo prebuild --platform android --no-install
          cd android
          # Включаем New Architecture, так как этого требует Reanimated 4
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m" > gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "hermesEnabled=true" >> gradle.properties
          echo "newArchEnabled=true" >> gradle.properties
          
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GhostMessenger-Debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
